import Head from "next/head";
// import Feed from "../components/Feed";
import Header from "../components/Header";
// import UploadModal from "../components/UploadModal";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <main className="flex px-5 p-3 lg:px-20 min-h-screen flex-col justify-start">
      <div className="min-h-screen">
        <Head>
          <title>IG</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Header */}

        <Header />

        {/* Feed */}
        
        <Feed />
        
      </div>
    </main>
  );
}
